# Generated by Django 4.2.7 on 2025-11-01 13:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(db_index=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('bike_shop', 'Bike Shop'), ('parking', 'Parking'), ('trailhead', 'Trailhead')], max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20)),
                ('length_km', models.FloatField()),
                ('elevation_gain_m', models.FloatField()),
                ('path', django.contrib.gis.db.models.fields.LineStringField(db_index=True, srid=4326)),
            ],
        ),
    ]
