# Generated by Django 5.2.7 on 2025-12-03 13:23

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtb_trails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='park',
            options={'ordering': ['name'], 'verbose_name': 'Mountain Bike Park', 'verbose_name_plural': 'Mountain Bike Parks'},
        ),
        migrations.AlterModelOptions(
            name='poi',
            options={'ordering': ['name'], 'verbose_name': 'Point of Interest', 'verbose_name_plural': 'Points of Interest'},
        ),
        migrations.AlterModelOptions(
            name='trail',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='park',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='park',
            name='description',
            field=models.TextField(blank=True, help_text='Details about the park, facilities, location information'),
        ),
        migrations.AddField(
            model_name='park',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('osm', 'OpenStreetMap'), ('other', 'Other Source')], default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='park',
            name='source_id',
            field=models.CharField(blank=True, help_text='External ID from data source (e.g., OSM way ID)', max_length=100),
        ),
        migrations.AddField(
            model_name='park',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='description',
            field=models.TextField(blank=True, help_text='Details about the POI, facilities, opening hours, etc.'),
        ),
        migrations.AddField(
            model_name='poi',
            name='park',
            field=models.ForeignKey(blank=True, help_text='Associated park (if POI is within/near a park)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='mtb_trails.park'),
        ),
        migrations.AddField(
            model_name='poi',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('osm', 'OpenStreetMap'), ('other', 'Other Source')], default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='poi',
            name='source_id',
            field=models.CharField(blank=True, help_text='External ID from data source (e.g., OSM node ID)', max_length=100),
        ),
        migrations.AddField(
            model_name='poi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trail',
            name='description',
            field=models.TextField(blank=True, help_text='Trail description, features, warnings, etc.'),
        ),
        migrations.AddField(
            model_name='trail',
            name='park',
            field=models.ForeignKey(blank=True, help_text='Parent park this trail belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='mtb_trails.park'),
        ),
        migrations.AddField(
            model_name='trail',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('osm', 'OpenStreetMap'), ('other', 'Other Source')], default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='trail',
            name='source_id',
            field=models.CharField(blank=True, help_text='External ID from data source (e.g., OSM relation ID)', max_length=100),
        ),
        migrations.AddField(
            model_name='trail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(db_index=True, help_text='Geographic boundary of the park area', srid=4326),
        ),
        migrations.AlterField(
            model_name='park',
            name='name',
            field=models.CharField(help_text="Park name (e.g., 'Ticknock Forest', 'Ballyhoura MTB Park')", max_length=100),
        ),
        migrations.AlterField(
            model_name='poi',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(db_index=True, help_text='Geographic location of the POI', srid=4326),
        ),
        migrations.AlterField(
            model_name='poi',
            name='name',
            field=models.CharField(help_text="POI name (e.g., 'Ticknock Car Park', 'Mountain View Cafe')", max_length=100),
        ),
        migrations.AlterField(
            model_name='poi',
            name='type',
            field=models.CharField(choices=[('bike_shop', 'Bike Shop'), ('parking', 'Parking'), ('trailhead', 'Trailhead'), ('cafe', 'Cafe/Restaurant'), ('viewpoint', 'Viewpoint'), ('rest_area', 'Rest Area'), ('toilets', 'Toilets'), ('water', 'Water Source'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trail',
            name='elevation_gain_m',
            field=models.FloatField(help_text='Total elevation gain in meters', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='trail',
            name='length_km',
            field=models.FloatField(help_text='Trail length in kilometers', validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='trail',
            name='name',
            field=models.CharField(help_text="Trail name (e.g., 'Ticknock Blue Trail', 'Black Diamond Run')", max_length=100),
        ),
        migrations.AlterField(
            model_name='trail',
            name='path',
            field=django.contrib.gis.db.models.fields.LineStringField(db_index=True, help_text='Trail route as a line geometry (sequence of coordinates)', srid=4326),
        ),
    ]
